apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: talana-sre-challenge-jesben
      auth:
        workloadIdentity:
          clusterLocation: us-east1
          clusterName: talana-gke-cluster
          clusterProjectID: talana-sre-challenge-jesben
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
