apiVersion: apps/v1
kind: Deployment
metadata:
  name: talana-backend
spec:
  template:
    spec:
      containers:
        - name: talana-backend
          env:
            - name: DJANGO_DEBUG
              value: "true"
