apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-api-crds.yaml
  - argo-rollouts.yaml
  - infra.yaml
  - cluster-secret-store.yaml
  - kong.yaml
  - dev-env.yaml
