apiVersion: apps/v1
kind: Deployment
metadata:
  name: talana-backend
  labels:
    app: talana-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talana-backend
  template:
    metadata:
      labels:
        app: talana-backend
    spec:
      serviceAccountName: talana-backend-sa
      containers:
        - name: talana-backend
          image: talana-backend
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DJANGO_DEBUG
              value: "false"
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
          envFrom:
            - secretRef:
                name: talana-backend-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /db-check
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
