apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: db-credentials-k8s
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: talana-db-connection
