apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - external-secret.yaml
  - ingress.yaml
  - kong-plugins.yaml

commonLabels:
  app.kubernetes.io/name: talana-backend
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: talana
