# Service principal (stable) - recibe tr치fico de producci칩n
apiVersion: v1
kind: Service
metadata:
  name: talana-backend-stable
  labels:
    app: talana-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: talana-backend
---
# Service canary - recibe tr치fico de prueba durante rollout
apiVersion: v1
kind: Service
metadata:
  name: talana-backend-canary
  labels:
    app: talana-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: talana-backend
---
# Service root (para Argo Rollouts) - no se usa para tr치fico directo
apiVersion: v1
kind: Service
metadata:
  name: talana-backend
  labels:
    app: talana-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: talana-backend
